In [14]:
%cd D:\git_projects\sentiment-analysis

D:\git_projects\sentiment-analysis


In [ ]:
# TASK 1: Loading the data set

In [11]:
import pandas as pd

df = pd.read_csv('IMDB Dataset.csv')
df.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [15]:
# BAG OF WORDS / BAG OF N-GRAMS MODEL
# Dataset is an even split, so Accuracy is an alright metric.

In [18]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

count = CountVectorizer()
# Example case
docs = np.array(['This is a sentence.', 'This is also a sentence.', 'These are all sentences!'])
bag = count.fit_transform(docs)

print(count.vocabulary_)
print(bag.toarray())

{'this': 7, 'is': 3, 'sentence': 4, 'also': 1, 'these': 6, 'are': 2, 'all': 0, 'sentences': 5}
[[0 0 0 1 1 0 0 1]
 [0 1 0 1 1 0 0 1]
 [1 0 1 0 0 1 1 0]]


In [24]:
# TERM FREQUENCY - INVERSE DOCUMENT FREQUENCY
from sklearn.feature_extraction.text import TfidfTransformer

np.set_printoptions(precision=2)

tfidf = TfidfTransformer(use_idf=True, norm='l2', smooth_idf=True)

print(tfidf.fit_transform(bag).toarray())

# Words should now be weighted. For example, if 'is' appears 5 times in one document, and also in all others, 
# the weight gets reduced from 5 to some smaller value, reflecting its probably lack of importance.

[[0.   0.   0.   0.58 0.58 0.   0.   0.58]
 [0.   0.6  0.   0.46 0.46 0.   0.   0.46]
 [0.5  0.   0.5  0.   0.   0.5  0.5  0.  ]]


In [26]:
# DATA PREPARATION - clear out useless stuff; punctuation, HTML tags and so on
import re

def preprocessor(text):
    text = re.sub('<[^>]*>', '', text)
    text = re.sub('[\W]+', ' ', text.lower())
#     emoticons = re.findall('(?::|;|=)(?:\)|\(|D|P)', text)
#   FUCK REGEX AND FUCK EMOTICONS
#   That's all the goddamn preprocessing I can fucking stomach.
#  Move emojis (emotes, emoticons? I don't fucking know anymore) to end in proper preprocessing. Lots of smileys is good
    return text

preprocessor("<br />Hello, children! :-)")


'hello children '